version: '3.1'
services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo_express:
      image: mongo-express
      ports:
        - 8081:8081
      depends_on:
        - mongo
      environment:
        ME_CONFIG_MONGODB_ADMINUSERNAME: root
        ME_CONFIG_MONGODB_ADMINPASSWORD: root
        ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/

  app:
      build:
        dockerfile: ./
        context: .
      image: ngosbrazil
      container_name: ngos-brazil
      ports:
        - 8080:8080
      depends_on:
        - mongo
        - mongo_express

